#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SuperMarket")]
	public partial class SuperMarketDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertNhaSanXuat(NhaSanXuat instance);
    partial void UpdateNhaSanXuat(NhaSanXuat instance);
    partial void DeleteNhaSanXuat(NhaSanXuat instance);
    #endregion
		
		public SuperMarketDataContext() : 
				base(global::DAL.Properties.Settings.Default.SuperMarketConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SuperMarketDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperMarketDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperMarketDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SuperMarketDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<NhaSanXuat> NhaSanXuats
		{
			get
			{
				return this.GetTable<NhaSanXuat>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_San_Pham;
		
		private string _Ten_San_Pham;
		
		private System.Nullable<System.DateTime> _Ngay_Nhap_Hang;
		
		private string _Ten_Mat_Hang;
		
		private string _Nha_San_Xuat;
		
		private System.Nullable<bool> _Tinh_Trang_Hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_San_PhamChanging(string value);
    partial void OnMa_San_PhamChanged();
    partial void OnTen_San_PhamChanging(string value);
    partial void OnTen_San_PhamChanged();
    partial void OnNgay_Nhap_HangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_Nhap_HangChanged();
    partial void OnTen_Mat_HangChanging(string value);
    partial void OnTen_Mat_HangChanged();
    partial void OnNha_San_XuatChanging(string value);
    partial void OnNha_San_XuatChanged();
    partial void OnTinh_Trang_HangChanging(System.Nullable<bool> value);
    partial void OnTinh_Trang_HangChanged();
    #endregion
		
		public SanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ma San Pham]", Storage="_Ma_San_Pham", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_San_Pham
		{
			get
			{
				return this._Ma_San_Pham;
			}
			set
			{
				if ((this._Ma_San_Pham != value))
				{
					this.OnMa_San_PhamChanging(value);
					this.SendPropertyChanging();
					this._Ma_San_Pham = value;
					this.SendPropertyChanged("Ma_San_Pham");
					this.OnMa_San_PhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ten San Pham]", Storage="_Ten_San_Pham", DbType="NVarChar(100)")]
		public string Ten_San_Pham
		{
			get
			{
				return this._Ten_San_Pham;
			}
			set
			{
				if ((this._Ten_San_Pham != value))
				{
					this.OnTen_San_PhamChanging(value);
					this.SendPropertyChanging();
					this._Ten_San_Pham = value;
					this.SendPropertyChanged("Ten_San_Pham");
					this.OnTen_San_PhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngay Nhap Hang]", Storage="_Ngay_Nhap_Hang", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngay_Nhap_Hang
		{
			get
			{
				return this._Ngay_Nhap_Hang;
			}
			set
			{
				if ((this._Ngay_Nhap_Hang != value))
				{
					this.OnNgay_Nhap_HangChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Nhap_Hang = value;
					this.SendPropertyChanged("Ngay_Nhap_Hang");
					this.OnNgay_Nhap_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ten Mat Hang]", Storage="_Ten_Mat_Hang", DbType="NVarChar(100)")]
		public string Ten_Mat_Hang
		{
			get
			{
				return this._Ten_Mat_Hang;
			}
			set
			{
				if ((this._Ten_Mat_Hang != value))
				{
					this.OnTen_Mat_HangChanging(value);
					this.SendPropertyChanging();
					this._Ten_Mat_Hang = value;
					this.SendPropertyChanged("Ten_Mat_Hang");
					this.OnTen_Mat_HangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nha San Xuat]", Storage="_Nha_San_Xuat", DbType="NVarChar(100)")]
		public string Nha_San_Xuat
		{
			get
			{
				return this._Nha_San_Xuat;
			}
			set
			{
				if ((this._Nha_San_Xuat != value))
				{
					this.OnNha_San_XuatChanging(value);
					this.SendPropertyChanging();
					this._Nha_San_Xuat = value;
					this.SendPropertyChanged("Nha_San_Xuat");
					this.OnNha_San_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tinh Trang Hang]", Storage="_Tinh_Trang_Hang", DbType="Bit")]
		public System.Nullable<bool> Tinh_Trang_Hang
		{
			get
			{
				return this._Tinh_Trang_Hang;
			}
			set
			{
				if ((this._Tinh_Trang_Hang != value))
				{
					this.OnTinh_Trang_HangChanging(value);
					this.SendPropertyChanging();
					this._Tinh_Trang_Hang = value;
					this.SendPropertyChanged("Tinh_Trang_Hang");
					this.OnTinh_Trang_HangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaSanXuat")]
	public partial class NhaSanXuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nha_San_Xuat;
		
		private string _San_Pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNha_San_XuatChanging(string value);
    partial void OnNha_San_XuatChanged();
    partial void OnSan_PhamChanging(string value);
    partial void OnSan_PhamChanged();
    #endregion
		
		public NhaSanXuat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nha San Xuat]", Storage="_Nha_San_Xuat", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nha_San_Xuat
		{
			get
			{
				return this._Nha_San_Xuat;
			}
			set
			{
				if ((this._Nha_San_Xuat != value))
				{
					this.OnNha_San_XuatChanging(value);
					this.SendPropertyChanging();
					this._Nha_San_Xuat = value;
					this.SendPropertyChanged("Nha_San_Xuat");
					this.OnNha_San_XuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_San_Pham", DbType="NChar(10)")]
		public string San_Pham
		{
			get
			{
				return this._San_Pham;
			}
			set
			{
				if ((this._San_Pham != value))
				{
					this.OnSan_PhamChanging(value);
					this.SendPropertyChanging();
					this._San_Pham = value;
					this.SendPropertyChanged("San_Pham");
					this.OnSan_PhamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
